package umlmodeling;

import java.awt.GridBagLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JLabel;


public class frmCanvas extends javax.swing.JFrame {
    int curX=0;
    int curY=0;
    int initialX=0;
    int initialY=0;
    int curLabelCount=0;
    boolean lineStarted=false;
    /** Creates new form frmCanvas */
    public frmCanvas() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setState(1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1_MousePressed(evt);
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel1_ComponentResized(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1_MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1_MouseReleased(evt);
            }
        });
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1_MouseDragged(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 60, 130));

        jLabel2.setText("jLabel1");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2_MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2_MouseReleased(evt);
            }
        });
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2_MouseDragged(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 130));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jTextField1.setBackground(new java.awt.Color(255, 255, 153));
        jTextField1.setText("jTextField1");
        jPanel2.add(jTextField1);
        jTextField1.setBounds(0, 0, 160, 20);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 160, 80));

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1_MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_MouseDragged
        // TODO add your handling code here:
         // TODO add your handling code here:
        System.out.println("B: " + evt.getButton() + ", " + evt.getX()+ ", " + evt.getY());
        if(evt.getButton()==0){
            if(jLabel1.getLocation().x!=evt.getX() || jLabel1.getLocation().y!=evt.getY())
                jLabel1.setLocation(evt.getXOnScreen() - jLabel1.getWidth()/2  , evt.getYOnScreen()- jLabel1.getHeight()/2- jPanel1.getY());
            
        }
        
    }//GEN-LAST:event_jLabel1_MouseDragged

    private void jLabel1_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel1_MousePressed

    private void jPanel1_ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1_ComponentResized
        // TODO add your handling code here:
        reSetDrawing();
    }//GEN-LAST:event_jPanel1_ComponentResized

    private void jLabel1_MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_MouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel1_MouseReleased

    private void jPanel1_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1_MousePressed
        // TODO add your handling code here:
        if(!lineStarted){
            initialX=evt.getX();
            initialY=evt.getY()  - jPanel1.getY();
            lineStarted=true;
        }
        else{
            jPanel1.getGraphics().drawLine(initialX, initialY, evt.getX(), evt.getY()- jPanel1.getY());        
            lineStarted=false;
            
        }
    }//GEN-LAST:event_jPanel1_MousePressed

    private void jLabel2_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2_MousePressed

    private void jLabel2_MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2_MouseReleased

    private void jLabel2_MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2_MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JTextField j=new javax.swing.JTextField();        
        curLabelCount++;
        int top=curLabelCount*20;        
        jPanel2.add(j);
        j.setText("Label" + curLabelCount);
        j.setBounds(0,top,jPanel2.getWidth(),20);
        j.setVisible(true);
        if((top+16)>jPanel2.getHeight()){
            jPanel2.setBounds(jPanel2.getX(), jPanel2.getY(), jPanel2.getWidth(), jPanel2.getHeight()+20);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    void reSetDrawing(){
       
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCanvas().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
