package umlmodeling;

public class frmCode extends javax.swing.JFrame {
    
    /** Creates new form frmCode */
    public frmCode(String code) {
        initComponents();
        txtCode.setText(code);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtCode = new javax.swing.JTextArea();
        cmdClose = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btnIf = new javax.swing.JButton();
        btnWhile = new javax.swing.JButton();
        btnWhile1 = new javax.swing.JButton();
        btnFunction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtCode.setColumns(20);
        txtCode.setRows(5);
        jScrollPane1.setViewportView(txtCode);

        cmdClose.setText("Close");
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        btnIf.setText("If-Else");
        btnIf.setFocusable(false);
        btnIf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIf.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIfActionPerformed(evt);
            }
        });
        jToolBar1.add(btnIf);

        btnWhile.setText("While Loop");
        btnWhile.setFocusable(false);
        btnWhile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWhile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnWhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWhileActionPerformed(evt);
            }
        });
        jToolBar1.add(btnWhile);

        btnWhile1.setText("For Loop");
        btnWhile1.setFocusable(false);
        btnWhile1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWhile1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnWhile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWhile1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnWhile1);

        btnFunction.setText("Function");
        btnFunction.setFocusable(false);
        btnFunction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFunction.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunctionActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFunction);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmdClose))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cmdCloseActionPerformed

    private void btnIfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIfActionPerformed
        
        txtCode.insert("\nif(){\n\t//TODO: Add True condition\n}\nelse{\n\t//TODO: Add false condition\n}", txtCode.getCaretPosition());
    }//GEN-LAST:event_btnIfActionPerformed

    private void btnWhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWhileActionPerformed
        
        txtCode.insert("\nwhile(true){\n\t//TODO: Add loop statements\n}", txtCode.getCaretPosition());
    }//GEN-LAST:event_btnWhileActionPerformed

    private void btnWhile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWhile1ActionPerformed
        // TODO add your handling code here:
        txtCode.insert("\nfor(int i = 0;i < 10;i++){\n\t//TODO: Add loop statements\n}", txtCode.getCaretPosition());
    }//GEN-LAST:event_btnWhile1ActionPerformed

    private void btnFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunctionActionPerformed
        // TODO add your handling code here:
        txtCode.insert("\nvoid newFunction(){\n\t//TODO: Add function body\n}", txtCode.getCaretPosition());
    }//GEN-LAST:event_btnFunctionActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCode("").setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFunction;
    private javax.swing.JButton btnIf;
    private javax.swing.JButton btnWhile;
    private javax.swing.JButton btnWhile1;
    private javax.swing.JButton cmdClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea txtCode;
    // End of variables declaration//GEN-END:variables
    
}
